name: Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    name: Release package

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set Git user
        run: |
          git config --global user.name "Zapal Bot"
          git config --global user.email "hello@zapal.tech"

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        id: install-deps
        run: pnpm i

      - name: Create Release PR / Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
