name: Release

on:
  workflow_dispatch:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release package

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        id: install-deps
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build package
        run: pnpm build

      - name: Setup Git user
        run: |
          git config user.name "Zapal"
          git config user.email "hello@zapal.tech"

      - name: Create Release PR / Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'ci: release new version'
          setupGitUser: false
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
